export const ADD = 'ADD'
export const DELETE = 'DELETE'
export const TOGGLE = 'TOGGLE'
export const TOGGLE_ALL = 'TOGGLE_ALL'
export const CLEAR_TODO = 'CLEAR_TODO'
export const EDIT_TODO = 'EDIT_TODO'
